spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.efec55b43f888a7b
            client-secret: 053127f9c98debbee565a6a8684217dea243f5dd
          google:
            client-id: 608357775386-14allpsfiu03qadbek70q1vronu5jt62.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile